---
- name: Create Multipass VMs for a Nomad cluster
  hosts: localhost

  tasks:
  - name: Read Nomad cluster node VM configuration from file
    include_vars:
      file: nomad-nodes.yml
      name: nomadnodes
  - name: Create keypair and cloud-init
    include_tasks: create-keys-and-cloudinit.yml
  - name: Create the Nomad cluster VMs
    include_tasks: delete-and-create-new-vm-tasks.yml
    vars:
      vmname: "{{ item.key }}"
      vmcreationparams: "{{ item.value }}"
    loop: "{{ nomadnodes | dict2items }}"
